name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths: 
      - apis/poi/

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/devopsoh/api-poi:${{ github.run_number }} -f apis/poi/web/Dockerfile
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/devopsoh/api-poi:${{ github.run_number }}
    - name: 'Deploy to Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhack06u2z0e9poi'
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/devopsoh/api-poi:${{ github.run_number }}'


